baseurl = "http://programming.ironsand.net"
languageCode = "ja-JP"
title = "答えを知りたい"
theme = "hugo_theme_beg"
googleAnalytics = ""
disqusShortname = ""
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "GitHub"
    url = "https://ironsand.github.com"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ironsand"

[params]
    description = "答えを知りたい"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
